import type { NextConfig } from "next";
import { API, DB_URL, MONGODB_DB, MONGOPASSWORD, MONGOUSER ,CLIENT_SIDE, SERVER_SIDE, GITHUB_CLIENT_ID, GITHUB_CLIENT_SECRET, NEXTAUTH_SECRET, GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET} from "./config";

const nextConfig: NextConfig = {
  env:{
    GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET,
    GITHUB_CLIENT_ID,
    GITHUB_CLIENT_SECRET,
    NEXTAUTH_SECRET,
    SERVER_SIDE,
    CLIENT_SIDE,
    DB_URL: DB_URL,
    MONGODB_DB: MONGODB_DB,
    API,
    MONGOPASSWORD,
    MONGOUSER
  }
};

export default nextConfig;
